services:
  postgres:
    container_name: gym-pass-pg
    image: bitnami/postgresql
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_NAME}